spring:
# 配置数据源及数据库连接池
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.25.28.7:3306/th_transaction?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: m_th_transaction
      password: rCBl5m
      hikari:
        minimum-idle: 10
        maximum-pool-size: 200
        connection-timeout: 10000
        auto-commit: true
        idle-timeout: 10000
        max-lifetime: 2000000
        validationTimeout: 3000
        leak-detection-threshold: 10000
        connection-test-query: SELECT 1

# mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 日志配置文件
logging:
  config: classpath:logback.xml


